"""Discrete PSF-bank nuisance treatment for nonlinear model comparison.

This module promotes the PSF-bank marginalization used for the SPIE 2026
proceedings study into supported code. A "bank" is a small discrete set of
candidate PSFs, generated by scaling a truth aberration configuration. Each
candidate is fit under both the smooth-lens and subhalo-lens hypotheses; the
per-candidate results are then combined into a profiled likelihood-ratio
statistic and a PSF-marginalized Bayesian evidence comparison.

Notes
-----
The combination rules preserved here are load-bearing for reproducing the
published SPIE results and must not be changed silently:

- Equal prior weight ``-log(n_candidates)`` is applied to every candidate
  of *both* hypotheses before the log-sum-exp, so the normalization cancels
  in the evidence difference.
- The profiled statistic maximizes each hypothesis over the bank
  *independently* (a standard profile-likelihood construction); the smooth
  and subhalo hypotheses may prefer different candidates.
- ``q_fit_psf_profile`` is clamped at zero.
- Detection thresholds are ``q >= 10`` (SCDD) and ``Delta log Z > 5``.
"""

from __future__ import annotations

__all__ = (
    "DEFAULT_PSF_BANK_SCALES",
    "STRONG_EVIDENCE_DELTA_LOG_Z_THRESHOLD",
    "PsfBankCandidateFit",
    "PsfBankSummary",
    "scale_psf_aberrations",
    "combine_psf_bank_fits",
)

import math
from dataclasses import dataclass
from typing import Any, Dict, Iterable, Optional, Sequence

from .likelihood_metrics import SCDD_Q_THRESHOLD

DEFAULT_PSF_BANK_SCALES = (0.0, 0.5, 1.0, 1.5)
"""Candidate scale factors used by the SPIE PSF bank (`tuple` of `float`).

Scale ``0.0`` is a perfect PSF; ``1.0`` is the truth-amplitude PSF.
"""

STRONG_EVIDENCE_DELTA_LOG_Z_THRESHOLD = 5.0
"""Strong-evidence threshold on the marginalized ``Delta log Z`` (`float`)."""


def _logsumexp(values: Iterable[float]) -> Optional[float]:
    """Return a numerically stable log-sum-exp, ignoring non-finite input."""
    vals = [float(val) for val in values if val is not None and math.isfinite(float(val))]
    if not vals:
        return None
    max_val = max(vals)
    return float(max_val + math.log(sum(math.exp(val - max_val) for val in vals)))


def _scale_numeric_tree(value: Any, scale: float) -> Any:
    """Scale every numeric leaf of a nested container by ``scale``."""
    if isinstance(value, dict):
        return {key: _scale_numeric_tree(val, scale) for key, val in value.items()}
    if isinstance(value, (list, tuple)):
        scaled = [_scale_numeric_tree(val, scale) for val in value]
        return type(value)(scaled) if isinstance(value, tuple) else scaled
    if isinstance(value, bool):
        return value
    if isinstance(value, (int, float)):
        return float(value)*float(scale)
    return value


def _has_nonzero_numeric(value: Any) -> bool:
    """Return `True` if any numeric leaf of a nested container is nonzero."""
    if isinstance(value, dict):
        return any(_has_nonzero_numeric(val) for val in value.values())
    if isinstance(value, (list, tuple)):
        return any(_has_nonzero_numeric(val) for val in value)
    if isinstance(value, bool):
        return False
    if isinstance(value, (int, float)):
        return abs(float(value)) > 0.0
    return False


def scale_psf_aberrations(aberrations: Dict[str, Any], scale: float) -> Dict[str, Any]:
    """Build a PSF-bank candidate by scaling aberration coefficients.

    Parameters
    ----------
    aberrations : `dict`
        A ``psf.aberrations`` configuration block containing the coefficient
        maps ``segment_pistons``, ``segment_tiptilts``, ``segment_hexikes``,
        and ``global_zernikes`` with their ``enable_*`` flags.
    scale : `float`
        Multiplicative factor applied to every coefficient. A scale of
        ``0.0`` produces a perfect-PSF candidate with empty coefficient
        maps and all families disabled.

    Returns
    -------
    scaled : `dict`
        A new aberrations block with scaled coefficients and ``enable_*``
        flags recomputed from the scaled content.
    """
    families = ("segment_pistons", "segment_tiptilts", "segment_hexikes", "global_zernikes")
    scaled = dict(aberrations)
    if float(scale) == 0.0:
        for family in families:
            scaled[family] = {}
            scaled[f"enable_{family}"] = False
        return scaled
    for family in families:
        scaled[family] = _scale_numeric_tree(aberrations.get(family, {}), float(scale))
        scaled[f"enable_{family}"] = _has_nonzero_numeric(scaled[family])
    return scaled


@dataclass(frozen=True)
class PsfBankCandidateFit:
    """Smooth and subhalo fit results for one PSF-bank candidate.

    Parameters
    ----------
    scale : `float`
        Candidate scale factor relative to the truth aberrations.
    log_l_smooth : `float` or `None`
        Maximum log likelihood under the smooth-lens model.
    log_l_subhalo : `float` or `None`
        Maximum log likelihood under the subhalo-lens model.
    log_evidence_smooth : `float` or `None`
        Bayesian log evidence under the smooth-lens model.
    log_evidence_subhalo : `float` or `None`
        Bayesian log evidence under the subhalo-lens model.
    success : `bool`, optional
        Whether both fits for this candidate completed successfully.
        Failed candidates are excluded from the combination.
    """

    scale: float
    log_l_smooth: Optional[float]
    log_l_subhalo: Optional[float]
    log_evidence_smooth: Optional[float]
    log_evidence_subhalo: Optional[float]
    success: bool = True


@dataclass(frozen=True)
class PsfBankSummary:
    """Combined PSF-bank statistics for one dataset.

    Parameters
    ----------
    n_candidates : `int`
        Total number of candidates in the bank.
    n_success : `int`
        Number of candidates with successful fits.
    log_l_smooth_profile : `float` or `None`
        Smooth-model log likelihood profiled (maximized) over the bank.
    log_l_subhalo_profile : `float` or `None`
        Subhalo-model log likelihood profiled over the bank.
    q_fit_psf_profile : `float` or `None`
        Profiled likelihood-ratio statistic, ``max(0, 2 Delta log L)``.
    log_evidence_smooth_psf_marg : `float` or `None`
        PSF-marginalized smooth-model log evidence.
    log_evidence_subhalo_psf_marg : `float` or `None`
        PSF-marginalized subhalo-model log evidence.
    delta_log_evidence_psf_marg : `float` or `None`
        Marginalized evidence difference, subhalo minus smooth.
    best_smooth_scale : `float` or `None`
        Candidate scale preferred by the smooth-model profile.
    best_subhalo_scale : `float` or `None`
        Candidate scale preferred by the subhalo-model profile.
    detected_fit_scdd_psf_profile : `bool` or `None`
        Whether ``q_fit_psf_profile`` meets the SCDD threshold.
    detected_evidence_psf_marg : `bool` or `None`
        Whether the marginalized evidence difference is strong.
    """

    n_candidates: int
    n_success: int
    log_l_smooth_profile: Optional[float]
    log_l_subhalo_profile: Optional[float]
    q_fit_psf_profile: Optional[float]
    log_evidence_smooth_psf_marg: Optional[float]
    log_evidence_subhalo_psf_marg: Optional[float]
    delta_log_evidence_psf_marg: Optional[float]
    best_smooth_scale: Optional[float]
    best_subhalo_scale: Optional[float]
    detected_fit_scdd_psf_profile: Optional[bool]
    detected_evidence_psf_marg: Optional[bool]


def combine_psf_bank_fits(candidates: Sequence[PsfBankCandidateFit]) -> PsfBankSummary:
    """Combine per-candidate fits into profiled and marginalized statistics.

    Parameters
    ----------
    candidates : `list` of `PsfBankCandidateFit`
        Fit results for every candidate in the bank, including failed ones.

    Returns
    -------
    summary : `PsfBankSummary`
        Profiled likelihood-ratio and PSF-marginalized evidence summary.

    Notes
    -----
    The equal prior weight ``-log(n_candidates)`` is defined over the full
    bank, while sums run over successful candidates only; with all fits
    successful the marginalization is exact. The weight is applied to both
    hypotheses, so it cancels in ``delta_log_evidence_psf_marg``.
    """
    if not candidates:
        raise ValueError("combine_psf_bank_fits requires at least one candidate")
    log_prior = -math.log(len(candidates))
    fitted = [cand for cand in candidates if cand.success]

    smooth_logz = _logsumexp(
        cand.log_evidence_smooth + log_prior
        for cand in fitted
        if cand.log_evidence_smooth is not None
    )
    subhalo_logz = _logsumexp(
        cand.log_evidence_subhalo + log_prior
        for cand in fitted
        if cand.log_evidence_subhalo is not None
    )

    smooth_fits = [cand for cand in fitted if cand.log_l_smooth is not None]
    subhalo_fits = [cand for cand in fitted if cand.log_l_subhalo is not None]
    best_smooth = max(smooth_fits, key=lambda cand: cand.log_l_smooth) if smooth_fits else None
    best_subhalo = max(subhalo_fits, key=lambda cand: cand.log_l_subhalo) if subhalo_fits else None
    log_l_smooth_profile = None if best_smooth is None else float(best_smooth.log_l_smooth)
    log_l_subhalo_profile = None if best_subhalo is None else float(best_subhalo.log_l_subhalo)

    q_fit = None
    if log_l_smooth_profile is not None and log_l_subhalo_profile is not None:
        q_fit = max(0.0, 2.0*(log_l_subhalo_profile - log_l_smooth_profile))
    delta_logz = None
    if smooth_logz is not None and subhalo_logz is not None:
        delta_logz = subhalo_logz - smooth_logz

    return PsfBankSummary(
        n_candidates=len(candidates),
        n_success=len(fitted),
        log_l_smooth_profile=log_l_smooth_profile,
        log_l_subhalo_profile=log_l_subhalo_profile,
        q_fit_psf_profile=q_fit,
        log_evidence_smooth_psf_marg=smooth_logz,
        log_evidence_subhalo_psf_marg=subhalo_logz,
        delta_log_evidence_psf_marg=delta_logz,
        best_smooth_scale=None if best_smooth is None else float(best_smooth.scale),
        best_subhalo_scale=None if best_subhalo is None else float(best_subhalo.scale),
        detected_fit_scdd_psf_profile=None if q_fit is None else q_fit >= SCDD_Q_THRESHOLD,
        detected_evidence_psf_marg=(
            None if delta_logz is None else delta_logz > STRONG_EVIDENCE_DELTA_LOG_Z_THRESHOLD
        ),
    )
